apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-19-daily-stat
  labels:
    app: covid-19-daily-stat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-19-daily-stat
  template:
    metadata:
      labels:
        app: covid-19-daily-stat
    spec:
      containers:
      - name: app
        image: ms/covid-19-daily-stat
        imagePullPolicy: Never
